#!/usr/bin/env bash
# ============================================================================
# Ralph Wiggum Launcher
# ============================================================================
# Generated by /decompose for: ralph-wiggum-integration
# Source: PRD-ralph-wiggum-integration-2025-01-13.md
# Stories: 32
# Estimated duration: ~48h
#
# Usage:
#   ./ralph.sh [options]
#
# Options:
#   --continue        Resume interrupted session
#   --dry-run         Show plan without execution
#   --max-iterations  Override default max iterations (default: 50)
#   --mode            Force mode: hook or script
#
# Examples:
#   ./ralph.sh                          # Auto-select mode, run all stories
#   ./ralph.sh --dry-run                # Preview execution plan
#   ./ralph.sh --continue               # Resume after interruption
#   ./ralph.sh --mode script --overnight # Force script mode for overnight
#
# ============================================================================

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
RALPH_LOOP="${PROJECT_ROOT}/src/scripts/ralph_loop.sh"
PRD_FILE="${SCRIPT_DIR}/prd.json"
PROMPT_FILE="${SCRIPT_DIR}/PROMPT.md"
PROGRESS_FILE="${SCRIPT_DIR}/progress.txt"

# Default settings
MAX_ITERATIONS="${MAX_ITERATIONS:-50}"
CALLS_PER_HOUR="${CALLS_PER_HOUR:-100}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Header
echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║${NC}  🚀 Ralph Wiggum — ralph-wiggum-integration                ${BLUE}║${NC}"
echo -e "${BLUE}╠════════════════════════════════════════════════════════════╣${NC}"
echo -e "${BLUE}║${NC}  Stories: 32 | Est: ~48h | Max iterations: ${MAX_ITERATIONS}            ${BLUE}║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Validate prerequisites
if [[ ! -f "$PRD_FILE" ]]; then
    echo -e "${RED}Error: prd.json not found at ${PRD_FILE}${NC}"
    exit 1
fi

if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: jq is required but not installed${NC}"
    echo "Install with: apt-get install jq (Linux) or brew install jq (macOS)"
    exit 1
fi

# Check if ralph_loop.sh exists (will be created in S04)
if [[ ! -f "$RALPH_LOOP" ]]; then
    echo -e "${YELLOW}Warning: ralph_loop.sh not found at ${RALPH_LOOP}${NC}"
    echo -e "${YELLOW}This script will be created in S04-mode-script${NC}"
    echo ""
    echo "For now, you can manually execute stories with:"
    echo "  /brief @${SCRIPT_DIR}/S01-mode-hook.md"
    echo ""
    exit 0
fi

# Execute ralph loop
exec "$RALPH_LOOP" \
    --prd "$PRD_FILE" \
    --prompt "$PROMPT_FILE" \
    --progress "$PROGRESS_FILE" \
    --max-iterations "$MAX_ITERATIONS" \
    --calls "$CALLS_PER_HOUR" \
    "$@"
