#!/bin/bash
# Ralph loop — generated by /decompose
# Run this script directly in terminal for context liberation between stories
#
# Project: Worktree Integration EPCI
# Generated: 2026-01-14
# Stories: 12
#
# Usage:
#   cd docs/specs/worktree-integration
#   ./ralph.sh
#
# To stop: Ctrl+C
#
# SECURITY WARNING:
#   This script uses --dangerously-skip-permissions for autonomous execution.
#   Recommended safeguards:
#   - Run in Docker container without network access
#   - Use Git worktree to isolate changes
#   - Review changes before merging to main branch

set -e

# Configuration
MAX_ITERATIONS=${MAX_ITERATIONS:-50}
PRD_FILE="./prd.json"
PROGRESS_FILE="./progress.txt"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "========================================"
echo "  Ralph Wiggum — Autonomous Executor"
echo "========================================"
echo ""
echo "PRD: $PRD_FILE"
echo "Max iterations: $MAX_ITERATIONS"
echo "Progress log: $PROGRESS_FILE"
echo ""

# Check PRD exists
if [ ! -f "$PRD_FILE" ]; then
    echo -e "${RED}Error: PRD file not found: $PRD_FILE${NC}"
    exit 1
fi

# Log start
echo "[$(date -Iseconds)] Ralph started" >> "$PROGRESS_FILE"

for ((i=1; i<=MAX_ITERATIONS; i++)); do
    echo ""
    echo -e "${YELLOW}=== Iteration $i ===${NC}"

    # Check if any stories remain
    PENDING=$(jq '[.userStories[] | select(.passes==false and .status!="blocked")] | length' "$PRD_FILE")
    COMPLETED=$(jq '[.userStories[] | select(.passes==true)] | length' "$PRD_FILE")
    TOTAL=$(jq '.userStories | length' "$PRD_FILE")

    echo "Progress: $COMPLETED/$TOTAL completed, $PENDING pending"

    if [ "$PENDING" -eq 0 ]; then
        echo -e "${GREEN}All stories complete!${NC}"
        echo "[$(date -Iseconds)] All stories complete" >> "$PROGRESS_FILE"
        exit 0
    fi

    # Get next story info for logging
    NEXT_STORY=$(jq -r '[.userStories[] | select(.passes==false and .status!="blocked")][0].id // "none"' "$PRD_FILE")
    NEXT_TITLE=$(jq -r '[.userStories[] | select(.passes==false and .status!="blocked")][0].title // "none"' "$PRD_FILE")

    echo "Next story: $NEXT_STORY — $NEXT_TITLE"
    echo "[$(date -Iseconds)] Starting $NEXT_STORY" >> "$PROGRESS_FILE"

    # Execute next story (fresh context each time)
    # WARNING: --dangerously-skip-permissions enables autonomous execution
    # NOTE: Use /epci:ralph-exec (plugin prefix required)
    OUTPUT=$(claude --dangerously-skip-permissions "/epci:ralph-exec --prd $PRD_FILE" 2>&1) || true

    # Show output (truncated if too long)
    if [ ${#OUTPUT} -gt 2000 ]; then
        echo "${OUTPUT:0:1000}"
        echo "... [truncated] ..."
        echo "${OUTPUT: -500}"
    else
        echo "$OUTPUT"
    fi

    # Check completion signals
    if echo "$OUTPUT" | grep -q '<promise>STORY_DONE</promise>'; then
        echo -e "${GREEN}Story $NEXT_STORY completed successfully${NC}"
        echo "[$(date -Iseconds)] $NEXT_STORY DONE" >> "$PROGRESS_FILE"
    elif echo "$OUTPUT" | grep -q '<promise>ALL_DONE</promise>'; then
        echo -e "${GREEN}All stories complete!${NC}"
        echo "[$(date -Iseconds)] ALL_DONE" >> "$PROGRESS_FILE"
        exit 0
    elif echo "$OUTPUT" | grep -q '<promise>STORY_BLOCKED</promise>'; then
        echo -e "${YELLOW}Story $NEXT_STORY blocked, continuing to next...${NC}"
        echo "[$(date -Iseconds)] $NEXT_STORY BLOCKED" >> "$PROGRESS_FILE"
    else
        echo -e "${RED}Story $NEXT_STORY failed or unknown status${NC}"
        echo "[$(date -Iseconds)] $NEXT_STORY FAILED" >> "$PROGRESS_FILE"
    fi

    # Small delay to avoid rate limiting
    sleep 2
done

echo ""
echo -e "${RED}Max iterations ($MAX_ITERATIONS) reached${NC}"
echo "[$(date -Iseconds)] Max iterations reached" >> "$PROGRESS_FILE"
exit 1
